Modified the compress_lecture script The rm_list now will be generated only with the flag -r argument. Improved the argument handling and restored the fps=1 of the output video

diff --git a/local/.local/bin/compress_lecture b/local/.local/bin/compress_lecture
--- a/local/.local/bin/compress_lecture
+++ b/local/.local/bin/compress_lecture
@@ -8,24 +8,45 @@
 # to delete them with
 # 		xargs rm -f < MKV_DIR/rm_list
 
-help(){
+help() {
 
 	# help and usage message
-	echo -e "usage: "$(basename $0)" MKV_DIR\n"
+	echo -e "usage: "$(basename $0)" [OPTIONS] MKV_DIR\n"
 
 	echo "Compress all .mkv files inside the folder and subfolder of MKV_DIR."
 	echo "Update a file MKV_DIR/.data_size with the size in MB of the MKV and WEBM."
-	echo "Generate a MKV_DIR/rm_list file with the list of all .mkv compressed."
-	echo -e "With that you can delete them with"
-	echo -e "\txargs rm -f < MKV_DIR/rm_list\n"
-
+	echo
 	echo "OPTIONS"
 	echo "  -h --help    print this help message"
+	echo "  -r           generate MKV_DIR/rm_list a file with the list of all .mkv compressed"
+
+	exit 0
 }
 
+function gen_rm_list() {
+	echo "[ Generating the rm_list ]"
+	rm_list=""
+	for vid in $mkv_files; do
+		if test -e "${vid%%.mkv}.webm"; then
+			rm_list="$rm_list $vid"
+		fi
+	done
+	echo $rm_list > $video_dir/rm_list
+}
+
+# reading line arguments
+generate_rm_list=0
+while [[ "$#" -gt 0 ]]; do
+    case $1 in
+        -h|--help) help ;;
+        -r) generate_rm_list=1 ;;
+         *) video_dir="$1" ;;
+    esac
+	shift
+done
+
 # Verify the user is correctly using this script
-test "$1" = "-h" -o "$1" = "--help" && help
-test -d "$1" && video_dir="$1" || { echo "ERROR: $1 is not a video directory"; exit 1; }
+test -d "$video_dir" || { echo "ERROR: $1 is not a video directory"; exit 1; }
 
 video_to_compress=""
 mkv_files=$(find $video_dir -type f -name "*.mkv" | sort)
@@ -43,7 +64,11 @@ for vid in $mkv_files; do
 done
 
 # if there is none video to compress exit
-test -n "$video_to_compress" || { echo "There is no file to compress" ; exit 0 ; }
+if test ! -n "$video_to_compress"; then
+	test $generate_rm_list -eq 1 && gen_rm_list
+	echo "There is no file to compress"
+	exit 0 
+fi 
 
 # start compressing if the user confirm
 echo -e "\nProceed with compression? (y/n)"
@@ -53,7 +78,7 @@ test ! $ans = "y" && exit 0
 echo "[ Start compressing ]"
 for vid in $video_to_compress; do
 	echo -e "...compressing \033[1m${vid##*/}\033[0m"
-	ffmpeg -i $vid -filter:v fps=5 -b:a 16k -loglevel fatal ${vid%%.mkv}.webm
+	ffmpeg -i $vid -filter:v fps=1 -b:a 16k ${vid%%.mkv}.webm
 done
 echo "[ Done compressing ]"
 
@@ -77,13 +102,6 @@ done
 
 sort -o $video_dir/.data_size $video_dir/.data_size 
 
-echo "[ Generating the rm_list ]"
-rm_list=""
-for vid in $video_to_compress; do
-	if test -e "${vid%%.mkv}.webm"; then
-		rm_list="$rm_list $vid"
-	fi
-done
-echo $rm_list > $video_dir/rm_list
+test $generate_rm_list -eq 1 && gen_rm_list
 
 exit 0
